matrix:
  include:
    - os: linux
      #dist: trusty
      env: PLATFORM=linux CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'cmake', 'gcc-4.9', 'g++-4.9' ]
    - os: osx
      env: PLATFORM=osx
      compiler: clang
      #osx_image: xcode7

before_install:
  - git submodule update --init --recursive

script:
  - cmake . -Bbuild
  - cmake --build build
